### ISSUE TITLE
Button no longer inherits color from theme

### ISSUE THREAD

**Issue by gpoitch** [material-components/material-components-web#1345]
According to the readme:
> By default an MDC Button will inherit its color from the theme

```css
:root {
  --mdc-theme-primary: #3fa9f5;
}
```

Since 0.21.0, this is no longer happening and the buttons are all black.
