### ISSUE TITLE
Add Support for a Persistent Drawer Below Toolbar

### ISSUE THREAD

**Issue by ErraticFox** [material-components/material-components-web#1547]
I was wanting to make a request for a persistent drawer that wouldn't affect the width of the toolbar, because it would open up below the toolbar. I would say that this perfectly follows suit with Material Guidelines as there are plenty of Material Designed websites that Google owns that have this feature. Two of these websites are [Google+](https://plus.google.com) and [Inbox by Google](https://inbox.google.com).

**Comment by lynnjepsen** [comment]
I think this is probably a valid feature request, but I need to check with our design team

**Comment by amsheehan** [comment]
I spoke to one of our designers and they think it is entirely reasonable to provide this behavior. We will put it in tracker and prioritize it accordingly. In the mean time if you would like to take a stab at the implementation we'd gladly review a pull request or talk through the solution over [Discord](https://discord.gg/KuPrNhA).

**Comment by ErraticFox** [comment]
I haven't made a component, but I have came up with a really nice and easy solution to doing this. 
```html
  <main class="mdc-typography">
    <header class="mdc-toolbar">
    </header>
    <div class="wrapper">
      <aside class="mdc-persistent-drawer">
      </aside>
      <div class="main">
      </div>
    </div>
  </main>
```
```css
html {
  height: 100%;
  display: flex;
}

body {
  display: flex;
  flex-direction: row;
  flex-grow: 1;
  overflow-x: hidden;
}

main {
  display: flex;
  flex-grow: 1;
  flex-direction: column;
}

.main {
  background-color: red;
}
```
