### ISSUE TITLE
Persistant Drawer cause page scrollbar visible under FF

### ISSUE THREAD

**Issue by kmmbvnr** [material-components/material-components-web#1574]
### What MDC-Web Version are you using?

0.22 (running demo page)

### What browser(s) is this bug affecting?

Firefox 56.0

### What OS are you using?

Linux/Ubuntu 16.04 64-bit 

### What are the steps to reproduce the bug?

Go to https://material-components-web.appspot.com/drawer/persistent-drawer.html under ff and see that page has vertical scrolling.

Same page under Chrome has no scrolling.

### What is the expected behavior?

No scrolling in FF, like in Chrome

### Any other information you believe would be useful?

I've got same behavior in my design. The scrolling caused by drawer component. In the devtools you can try drop the class of `<nav class="mdc-persistent-drawer__drawer">` and see that the scrolling disappear.

**Comment by anton-kachurin** [comment]
You can add the following to your CSS to fix this in FF:

```CSS
.mdc-persistent-drawer {
  display: none;
}

.mdc-persistent-drawer .mdc-persistent-drawer--open {
    display: flex;
}
```
