### ISSUE TITLE
mdc-select__label wont get primary color

### ISSUE THREAD

**Issue by englishextra** [material-components/material-components-web#2409]
Even if you load the compiled CSS and replace manually all default `#6200ee` to custom `#0071CE` (see the screenshot), the mdc-select__label being focused gets default `#6200ee` text color.
![2018-03-15_110616](https://user-images.githubusercontent.com/537127/37451646-327a31c2-2843-11e8-8625-d008716cde7d.png)
I couldn't figure out where this color `#6200ee` comes from.

I searched in all compiled js and replaced `#6200ee` in compiled CSS, but to no avail.

the theme is compiled like so:
```scss
$mdc-theme-primary: #0071CE;
$mdc-theme-secondary: #0089F9;
$mdc-theme-background: #FFFFFF;

@import "../node_modules/@material/theme/mdc-theme";
```
the hack:
```scss
.mdc-select .mdc-select__surface.mdc-ripple-upgraded .mdc-select__label,
.mdc-select .mdc-select__surface.mdc-ripple-upgraded.mdc-ripple-upgraded--background-focused .mdc-select__label,
.mdc-select .mdc-select__surface.mdc-ripple-upgraded .mdc-select__label.mdc-select__label--float-above,
.mdc-select .mdc-select__surface.mdc-ripple-upgraded.mdc-ripple-upgraded--background-focused .mdc-select__label.mdc-select__label--float-above {
	color: rgba(0, 0, 0, 0.54);
	color: var(--mdc-theme-primary, rgba(0, 0, 0, 0.54));
}
```
source code: https://github.com/englishextra/serguei-material-dev
