### ISSUE TITLE
Figure out how to call Sass mixins from other components, within the baseline of a parent component

### ISSUE THREAD

**Issue by lynnmercier** [material-components/material-components-web#2415]
Take this made up example of the `mdc-foo` component using the `mdc-bar` component in its internal implementation:
```html
<div class="mdc-foo">
  <div class="mdc-bar"></div>
</div>
```
And there exists some Sass mixin to customize the color of mdc-bar
```scss
@mixin mdc-bar-color($color) {
  color: $color;
}
```

Now lets say that the `mdc-foo` component wants to have a blue `mdc-bar` in the default state, but a red `mdc-bar` in the invalid state. Then the stylesheet for `mdc-foo` has
```scss
.mdc-foo {
  .mdc-bar {
    @include mdc-bar-color(blue);
  }
}
.mdc-foo--invalid {
  .mdc-bar {
    @include mdc-bar-color(red);
  }
}
```
which outputs this CSS, once Sass is compiled.
```css
.mdc-foo  .mdc-bar {
  color: blue;
}
.mdc-foo--invalid .mdc-bar {
  color: red;
}
```

...so far so good...

The problem is if we change the implementation of `mdc-bar` so that it has a sub-element
```html
<div class="mdc-bar">
  <div class="mdc-bar__sub"></div>
</div>
```
And we have to update the implementation of the Sass mixin `mdc-bar-color`
```scss
@mixin mdc-bar-color($color) {
  .mdc-bar__sub {
    color: $color;
  }
}
```
All these changes happen in the `mdc-bar` node module, and none of them are breaking changes...but now the `mdc-foo` stylesheet outputs
```css
.mdc-foo  .mdc-bar .mdc-bar__sub {
  color: blue;
}
.mdc-foo--invalid .mdc-bar .mdc-bar__sub {
  color: red;
}
``` 
*which is unnecessarily specific*

How do we handle this case more gracefully?
