### ISSUE TITLE
Drawer does not show the right shape.

### ISSUE THREAD

**Issue by bifunctor** [material-components/material-components-web#2866]
Hi all 
I am trying to use Drawer as following: 

```Html
    <div className="content">
      <nav className="mdc-drawer mdc-drawer--permanent mdc-typography">
        <nav className="mdc-list">
          <a className="mdc-list-item mdc-list-item--activated" href="#">
            <i className="material-icons mdc-list-item__graphic" ariaHidden=true>{ReasonReact.string("inbox")}</i>
            {ReasonReact.string("Inbox")}
          </a>
          <a className="mdc-list-item" href="#">
            <i className="material-icons mdc-list-item__graphic" ariaHidden=true>{ReasonReact.string("star")}</i>
            {ReasonReact.string("Star")}
          </a>
        </nav>
      </nav>
      <main>
      {ReasonReact.string("amaii")}
      </main>
    </div>
```

The scss file looks like:

```Scss
@import "~material-design-icons/iconfont/material-icons.css";
@import "~@material/drawer/mdc-drawer.scss";


.content {
  display: flex;
  height: 100%;
}
```  

And it shows: 

![screenshot from 2018-06-03 00-07-08](https://user-images.githubusercontent.com/34632165/40881254-1e1b99ec-66c2-11e8-9cdd-a90fb3e0a4a7.png)  

As you can I, the styling is missing. But I imported all `Drawers` package component.
![screenshot from 2018-06-03 00-09-09](https://user-images.githubusercontent.com/34632165/40881265-661a72b8-66c2-11e8-82af-33c94be6f606.png)

Version: 

>     "@material/drawer": "^0.35.0",
>     "@material/layout-grid": "^0.34.0",   

Thanks
