### ISSUE TITLE
Add a `mdc-drawer--rail` variant

### ISSUE THREAD

**Issue by lynnmercier** [material-components/material-components-web#2874]
- [ ] Only shows the icons
- [ ] Animations for expanding/collapsing the rail drawer
- [ ] Update `MDCDismissibleDrawerFoundation` to handle the `mdc-drawer--rail` variant

Note: dismissible + rail can only be expanded/collapsed between icon-only and icon-with-label state, not fully dismissed. (i.e. "dismissible to rail")

**Comment by kfranqueiro** [comment]
Hey, I happened to ask one of our designers about this yesterday. No updates yet and I think design is currently focused on other components, but he'll be sure to let me know when they can come back to this.

**Comment by ITforHome** [comment]
thanks for this update. 
Do you have an idea, how can i implemente a drawer, there only shows icons and not text?

**Comment by mattdemler** [comment]
+1

**Comment by deap82** [comment]
@lynnmercier @ITforHome 

I've built this kind of menu responsively when using the permanent drawer, ie for large screens the menu is visible, for medium screens I have this version you call "rail", I call it "collapsible", and then I use mdc-drawer--modal for phone.

This scss should get you started, please note however that this will make the menu slide out on top of the other UI so it's more like the modal drawer then the dismissable drawer in that aspect.

```scss
@import "../../node_modules/@material/animation/functions"; //You might need to change this import to match your setup

.mdc-drawer:not(.mdc-drawer--modal) {
	@include whenCollapsibleDrawer() { //Media query for when you want the collapsible drawer, or remove if you always want it
		transition: mdc-animation-exit-temporary(width, 180ms);
		width: 52px; //The width of the menu when only icons are visible
		z-index: 1; //You might need to experiment with this value or not set it at all
		overflow: hidden;

		.collapsible-toggler { //First element inside .mdc-drawer__content, before .mdc-list: <button type="button" class="material-icons visible-collapsible-drawer collapsible-toggler" aria-label="Main menu" /* AURELIA SPECIFICS, refactor to js solution of your choice */ click.trigger="toggleCollapsibleDrawer()" aria-expanded.bind="collapsibleDrawerOpen" /* /AURELIA SPECIFICS */></button>
			position: absolute;
			display: block;
			height: 47px !important; //You might need to experiment with this value or not set it at all
			width: 100% !important; //You might need to experiment with this value or not set it at all
			border-bottom: solid 1px $grayLight; //You might need to experiment with this value or not set it at all
			cursor: pointer; //In my setup I exclude this for touch devices

			&:before {
				content: 'menu'; //Material icon name when menu only shows icons
				speak: none;
				color: blue; //Color of toggler icon
				height: 24px;
				width: 24px;
				position: absolute;
				right: 16px; //You might need to experiment with this value or not set it at all
				top: 13px; //You might need to experiment with this value or not set it at all
			}
		}

		&.collapsible-open {
			transition: mdc-animation-enter(width, 180ms);
			width: 294px; //Width of drawer when opened

			.collapsible-toggler {
				&:before {
					content: 'arrow_back'; //Material icon name for toggler when menu is opened
				}
			}
		}
	}
}

.visible-collapsible-drawer {
	display: none !important;
}

@include whenCollapsibleDrawer() { //Same media query as mentioned above or remove usage of the .visible-collapsible-drawer class if you always want the collapsible drawer
	.visible-collapsible-drawer {
		display: block !important;
	}
}
```
