### ISSUE TITLE
TextField/Select: Outlined variants can cause horizontal scrolling

### ISSUE THREAD

**Issue by robcaldecottvelo** [material-components/material-components-web#4057]
MDC 0.40.1, tested on Chrome/Safari (MacOS 10.14.1)

If you change the width of an outlined text field or select you can end up with unwanted horizontal scrolling on your page. For example, we often make text fields/selects 100%l wide on mobile and this results in extra space being added to the right of the component. I think this might be due to a `noflip` code change deep in the MDC ripple SASS.

Here is a codesandbox example that uses RMWC/MDC 0.40.1:

https://codesandbox.io/s/r4o71q26qp

Run the app and using the mouse you will be able to scroll the page horizontally exposing white space to the right of the component. This seems to be caused in part by the following CSS (in the case of a text field):

```css
.mdc-text-field::before, .mdc-text-field::after {
    top: calc(50% - 100%);
    left: calc(50% - 100%);
    width: 200%;
    height: 200%;
}
```

That `width: 200%` seems to be the problem, but I think there is more to it than that. My only workaround is to remove it using a custom CSS rule. I've tried `overflow-x: hidden` to no avail.

Note that `box` variant text fields and selects do not suffer from this issue yet it has the same CSS...!

Any ideas how to circumvent this correctly would be welcome.

**Comment by namannehra** [comment]
I had the same issue. I'm currently solving it with
```css
.mdc-text-field::before, .mdc-text-field::after {
    content: none;
}
```
What are `::before` and `::after`  pseudo-element being used for?
