### ISSUE TITLE
Ordering of animation shorthand breaks css-module build

### ISSUE THREAD

**Issue by tomdye** [material-components/material-components-web#4283]
## Bugs

I am attempting to compose mdc text field classes into a css-module file. When building this file with local names turned on, the css-module parser is unable to parse some of the animation shorthand used. This is because the css-module parser requires animation shorthand to specify the animation name before the timing / duration etc.

It appears that this could be rectified by updating two scss mixins to return animation styles with the animation name at the front.

These two files are:

- `packages/mdc-checkbox/_mixins.scss`
- `packages/mdc-ripple/_mixins.scss`

Making this change would allow developers using css-modules to style their components using the mdc library and should not diversely effect anyone else.

### What MDC Web Version are you using?

0.42.1

### Example of proposed change

Source: https://github.com/material-components/material-components-web/blob/master/packages/mdc-ripple/_mixins.scss#L124

#### Before

``` scss
@include mdc-feature-targets($feat-animation) {
	&.mdc-ripple-upgraded--foreground-activation::after {
		animation:
		$mdc-ripple-translate-duration mdc-ripple-fg-radius-in forwards,
		$mdc-ripple-fade-in-duration mdc-ripple-fg-opacity-in forwards;
	}
}
```

#### After

``` scss
@include mdc-feature-targets($feat-animation) {
	&.mdc-ripple-upgraded--foreground-activation::after {
		animation:
		mdc-ripple-fg-radius-in $mdc-ripple-translate-duration forwards,
		mdc-ripple-fg-opacity-in $mdc-ripple-fade-in-duration forwards;
	}
}
```
