### ISSUE TITLE
MDCTextField, MDCSelect floating label broken when inside MDCDialog with having a pre filled value

### ISSUE THREAD

**Issue by MrSimmmons** [material-components/material-components-web#4328]
## Bugs

Having pre filled values inside a notched outline versions of MDCTextField and MDCSelect elements doesn't seem to show them.
For some reason the extra width style that is applied to make the notch wide enough for the text just starts out at 0. If you go into inspect element and manually change the extra style that is applied to the notch, the label will show up.

### What MDC Web Version are you using?

> 0.43.1

### What browser(s) is this bug affecting?

> Chrome

### What OS are you using?

> MacOS

### What are the steps to reproduce the bug?

> Put a pre-filled notched outlined version of MDCTextField or MDCSelect inside a dialog
>
> [CodePen](https://codepen.io/anon/pen/LqxrJy)

### What is the expected behavior?

> The label shows up

### What is the actual behavior?

> The labels don't show up
### Any other information you believe would be useful?

This only seems to effect the text field and select elements when they is inside a dialog as the background text field and select elements use the exact same code and work fine
<img width="526" alt="screen shot 2019-02-01 at 2 09 56 am" src="https://user-images.githubusercontent.com/26075792/52056226-85cbf780-25c6-11e9-8699-b2c7f4d3a079.png">

**Comment by CyborgSemon** [comment]
Ah awesome thank you @kfranqueiro!
On a side note, any idea why this happens? The floating label getting cut off.

<img width="596" alt="screen shot 2019-02-01 at 12 52 48 pm" src="https://user-images.githubusercontent.com/26075792/52093561-74afd480-2620-11e9-8a56-62099e06c451.png">

It happens in both of our code pens

**Comment by kfranqueiro** [comment]
This is happening because the floating label for outlined text fields extends slightly beyond the top of the text field itself, meanwhile MDC Dialog's content area has no top padding as long as there's no scrolling, but also sets `overflow: auto` so that the content _can_ scroll if it gets too tall.

I wonder if we could move some of the padding from the title region to the content region of the dialog while still preserving the current styles when scrolling is present.

**Comment by cintaccs** [comment]
The cutting off the floating label will occur in any "container" not only dialog content section. Setting a margin-top:10px on the mdc-select element will solve it in general. Maybe worth to consider instead of specific to each container.

**Comment by jvalst** [comment]
Same issue with the notch over here. We're using some mdc expansion boxes with different mdc components in it. Is it possible to add something in the outlined textfields / selects that if they're visible the layout() function will be called anyways?

**Comment by ota-meshi** [comment]
I solved this issue using the following CSS.

```css
.mdc-notched-outline__notch {
  /* Ignore the width set by script, and change it to be calculated from the width of `mdc-floating-label` by setting `auto`. */
  width: auto !important;
}

.mdc-notched-outline__notch > label.mdc-floating-label--float-above {
  /* Remove `scale(0.75)` to apply the correct width to `mdc-notched-outline__notch`. */
  transform: translateY(-130%);

  /* Calculate `scale(0.75)` with each property. */
  font-size: calc(1rem * 0.75);
  top: calc(17px * (1 - ((1 - 0.75) / 2)));
}

/* with leading-icon */
.mdc-text-field--with-leading-icon .mdc-notched-outline__notch > label.mdc-floating-label--float-above {
  transform: translateY(-130%) translateX(-32px);
  font-size: calc(1rem * 0.75); /* Re-apply the above selector because the score is low. */
}

.mdc-notched-outline__notch > label.mdc-floating-label {
  transition:
    transform 150ms cubic-bezier(0.4, 0, 0.2, 1),
    color 150ms cubic-bezier(0.4, 0, 0.2, 1),
    /* Now that we calculate `scale(0.75)` for each property, we add each property to the target of the animation. */
    font-size 150ms cubic-bezier(0.4, 0, 0.2, 1),
    top 150ms cubic-bezier(0.4, 0, 0.2, 1);
}

```
