### ISSUE TITLE
MDC Tabs: Icons turning black instead of purple.

### ISSUE THREAD

**Issue by Richienb** [material-components/material-components-web#4538]
### What MDC Web Version are you using?

> 1.0.1

### What browser(s) is this bug affecting?

> All browsers

### What OS are you using?

> Windows 10

### What are the steps to reproduce the bug?

1. Open [this codepen](https://codepen.io/Richienb/full/ZPwXMo).
2. Start changing tabs.

### What is the expected behaviour?

> The tab icons should change in accordance with the selected tab.

### What is the actual behaviour?

> The tab icons turn black instead of purple when selected.

**Comment by Richienb** [comment]
A workaround seems to be:
```css
.mdc-tab.mdc-tab--active svg.mdc-tab__icon {
  fill: var(--mdc-theme-primary, #6200ee);
}
```
