### ISSUE TITLE
TextField fullWidth prop missing left padding with leading icon enabled

### ISSUE THREAD

**Issue by dohomi** [material-components/material-components-web#4640]
### What MDC Web Version are you using?

Latest

### What browser(s) is this bug affecting?

All versions

### What OS are you using?

All versions

### What are the steps to reproduce the bug?

Add a leading icon to the TextField with `fullwidth` enabled. 

### What is the expected behavior?

There should be left padding on the input field to show the icon

### What is the actual behavior?

Icon overlaps.

Currently I fix it with CSS
```css
.mdc-text-field--with-leading-icon.mdc-text-field--fullwidth .mdc-text-field__input {
  padding-left: 48px !important; /* fixing misaligned input field on fullWidth TextField */
}
```

**Comment by moog16** [comment]
I'm seeing this: 

<img width="334" alt="Screen Shot 2019-04-26 at 11 48 11 AM" src="https://user-images.githubusercontent.com/579873/56829650-325df400-6819-11e9-9f27-5ff37090932c.png">

Can you confirm this is also what you're seeing?

**Comment by moog16** [comment]
@dohomi ping :)

**Comment by dohomi** [comment]
@moog16 thats exactly what I see as well. Fixed it with the work around above but not sure if it respects accurately Googles spec on margin/padding

**Comment by moog16** [comment]
We actually don't have any guidance on this setup. We need design guidance.

**Comment by abhiomkar** [comment]
Design says full width text field variant can have leading / trailing icon.

Adding this to icebox.

**Comment by martinoppitz** [comment]
I think that this definition must be removed.

```css
.mdc-text-field--fullwidth:not(.mdc-text-field--textarea) .mdc-text-field__input {
    padding: 0;
}
```
