### ISSUE TITLE
I can't setup dark or light mode during runtime which because some @mix take constant parameter

### ISSUE THREAD

**Issue by leecjson** [material-components/material-components-web#4793]
```scss
--my-text-color: var(--mdc-theme-text-primary-on-light);

@include mdc-button-ink-color(var(--my-text-color));     // pass
@include mdc-states(var(--my-text-color));    // build with an error

&[dark] {
    --my-text-color: var(--mdc-theme-text-primary-on-dark);
}
```
