### ISSUE TITLE
[MDCDrawer] Add build-in support for change drawer type at runtime

### ISSUE THREAD

**Issue by m-alzam** [material-components/material-components-web#4802]
## Feature Request

Hello. I'am working on a app that should be adapted depending of the user's screen size. It uses a Drawer to show the navigation menu. The problem is the following: if I use a Modal Drawer, the user needs to click on the menu button to open it when he's in a large screen. Mobile users don't have this problem. To solve the problem, I can use a Dismissible Drawer, but it's not designed to mobile devices.

Is it possible to add a new element (like Responsive Drawer) that changes depending on the screen size? Or there's a easy way to change the type of Drawer using css `@media`? The Material Design specification says that "[Modal Drawer] can be replaced by standard drawers on tablet and desktop", but it is not easy to do in web (or I don't know how).

### Proposed solution

IMHO, adding a new type of Drawer is the easier solution. It's a good idea to add a section in the [Drawer Web Component](https://material.io/develop/web/components/drawers/) to help developers, showing a way to use a "responsive" drawer that adapts itself depending of the screen.

The #590 issue is similar to this, but it doesn't show a clear solution to the problem.

Thanks in advance.

**Comment by abhiomkar** [comment]
Thanks for the suggestion Manuel! 

Please see example on Glitch for responsive drawer:
https://glitch.com/~material-responsive-drawer 

We can link this example to our drawer README file, since this is requested frequently. 

PR Welcome :)

**Comment by samstride** [comment]
That was a useful example. Thanks.

Is there an example where the dismissible drawer is below the top app bar (ex: https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer#dismissible-drawer-below-top-app-bar) for non-mobile screens and switches to modal drawer for mobile screens?

**Comment by youbet1980** [comment]
Yes like @samstride says I am looking for something that works exactly the same as news.google.com
Eg:
The Dismissible Drawer appears Non Modal when in desktop. ( But can still be hidden )
and as soon as it goes to tablet or mobile view it becomes modal.

**Comment by m-alzam** [comment]
Hello.
If I have time this summer, I will try to create   a MDCResponsibleDrawer or something similar, @abhiomkar.
Thanks

**Comment by m-alzam** [comment]
Hello
I have styling the MDCDrawer component to be responsive, but I don't know who to create or modify a component, so I decided to put the code here and ask if someone can help me.

CSS:
```scss
.mdc-drawer {
  position: inherit;
}

.mdc-drawer-scrim {
  display: none;
  visibility: hidden;
  background-color: rgba(0, 0, 0, 0.32);
  z-index: 7;
}

.mdc-drawer__header {
  display: none;
}

// Mobile
@media (max-width: 600px) {
  .mdc-drawer {
    z-index: 10;
    padding-top: 0;
    position: fixed;
  }

  .mdc-drawer-scrim {
    visibility: visible;
  }
  
  .mdc-drawer__header {
    display: block;
  }

}
```

JS
```js
document.querySelector(".mdc-drawer-scrim").addEventListener("click", () => {
    drawer.open = !drawer.open;
});
```

And the final result:

![result](https://user-images.githubusercontent.com/47950933/61456198-c5fd1780-a965-11e9-9dd8-ef7375faf374.gif)
