### ISSUE TITLE
[mdc-ripple] hasPseudoVarBug check (border-top-style: solid) is causing compat issues with tailwind css

### ISSUE THREAD

**Issue by wc-matteo** [material-components/material-components-web#5061]
The `hasPseudoVarBug` check [here](https://github.com/material-components/material-components-web/blob/9e8747840594dd435e04220dc9f4aa31eb153a88/packages/mdc-ripple/util.ts#L46) is causing issues (i.e. the ripple doesn't appear) when using [tailwindcss](https://tailwindcss.com/).

The problematic css comes from tailwind's [base styles](https://tailwindcss.com/docs/preflight#border-styles-are-reset-globally):

```css
*,
*::before,
*::after {
  border-width: 0;
  border-style: solid;
  border-color: #e2e8f0;
}
```
