### ISSUE TITLE
[snackbar] Mixin mdc-snackbar-fill-color($color) doesn't produce any code

### ISSUE THREAD

**Issue by kintz09** [material-components/material-components-web#5205]
I'm trying to customize the snackbar which I just added to my project. I am successfully using the mixin `mdc-snackbar-z-index($z-index)` but the others that depend on the theme package are not working. I'm not getting any compiler error or console errors, those mixins just don't do anything.

Project Info:
- React
- Typescript
- Webpack
- node-sass
- @material/theme@1.1.0
- @material/snackbar@1.1.1

Here's the SCSS file where I'm using the mixin:

_Snackbar.module.scss_
```scss
@import "@material/snackbar/mixins";

.snackbar {
 @include mdc-snackbar-fill-color(#ffffff);
 @include mdc-snackbar-z-index(1000);
}
```

This is the class that is ultimately generated on build:
```css
.snackbar {
z-index: 1000;
}
```
Notice that there is no code related to the `mdc-snackbar-fill-color` mixin created. It's like it completely ignored that mixin. I looked into the mixin functions defined in the `theme` and `snackbar` packages and noticed something interesting. The mixin function for z-index is basic and self-contained, but the fill-color mixin calls another mixin from the @material/theme package. Here's the relevant mixin functions from snackbar package:

_snackbar/__mixins.scss_
```scss
@import "@material/elevation/mixins";
@import "@material/shape/mixins";
@import "@material/theme/mixins";
@import "./variables";

@mixin mdc-snackbar-fill-color($color) {
  .mdc-snackbar__surface {
    @include mdc-theme-prop(background-color, $color);

@mixin mdc-snackbar-z-index($z-index) {
  z-index: $z-index;
}
```
Since the z-index mixin is working along with other mixins that don't reference another package, this leads me to believe that the snackbar package may not be finding the `mdc-theme-prop(background-color, $color)` mixin from the theme package. The snackbar and theme components are both installed at the root of the node_modules/@material directory.

Could this be a webpack or typescript config issue? Or is this possibly just a bug? I'd love to just upgrade all these packages to 3.0 but I'm using the official React wrapper components which are still on 1.x. 

If there is any additional troubleshooting or information I can provide, please let me know. I greatly appreciate any advice anyone has for me on this issue.
