### ISSUE TITLE
[MDCLinearProgress] animate buffer dots only when necessary

### ISSUE THREAD

**Issue by dessant** [material-components/material-components-web#5294]
The buffer dots are animated even when `progress` or `buffer` are set to 1, or `buffer` is not set at all. This causes significant CPU utilization on Firefox, while having a negligible performance impact on Chrome.

The buffer dots should be animated only when they are visible, disabling the animation has fixed the performance issues of a static progress bar on my part.

```css
.mdc-linear-progress__buffering-dots {
  animation: none;
}
```
