### ISSUE TITLE
[MDCTextField] Outlined label position incorrect with `mdc-text-field--fullwidth`

### ISSUE THREAD

**Issue by mashirozx** [material-components/material-components-web#5334]
## Bug report

Outlined label position incorrect with `mdc-text-field--fullwidth`:
![image](https://user-images.githubusercontent.com/16148054/70780735-30549f80-1dc0-11ea-809d-c6f683d06733.png)

### Steps to reproduce
```html
   <div class="fields">
      <div class="author">
        <div class="mdc-text-field mdc-text-field--outlined mdc-text-field--fullwidth">
          <input class="mdc-text-field__input" id="text-field-hero-input">
          <div class="mdc-notched-outline">
            <div class="mdc-notched-outline__leading"></div>
            <div class="mdc-notched-outline__notch">
              <label for="text-field-hero-input" class="mdc-floating-label">Name</label>
            </div>
            <div class="mdc-notched-outline__trailing"></div>
          </div>
        </div>
      </div>
      <div>...The same div loop here</div>
   </div>
```

```scss
    .fields {
      width: 100%; /*parent is flex row layout*/
      height: 100%; /*100% of parent with a px fixed height*/
      background: tomato;
      display: -webkit-flex;
      display: flex;

      >* {
        width: 100%;
        height: 100%;
      }
    }
```

### Actual behavior

![image](https://user-images.githubusercontent.com/16148054/70780735-30549f80-1dc0-11ea-809d-c6f683d06733.png)

### Expected behavior

Label display in correct height/top/margin (whatever), whild `mdc-text-field` has a 100% width of parent.

Picture below, just remove the `mdc-text-field--fullwidth` class from the first field.
![image](https://user-images.githubusercontent.com/16148054/70781762-1f585e00-1dc1-11ea-9980-12236e34b6a5.png)

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          |4.0.0|
| Browser          |Chrome 78.0.3904.108|
| Operating System |Windows 10|
