### ISSUE TITLE
[mdc-button] Outline color is not set to primary by default

### ISSUE THREAD

**Issue by kimurakenshi** [material-components/material-components-web#5650]
## Bug report
For the outlined button the `border-color` is not longer set to primary color. Now is using `on-surface` instead.

### Steps to reproduce

Just take a look at the border color of the outlined button to notice that is not using the primary color.

### Expected behavior
Unless the spec has changed and i'm not aware of that i would say this should use the primary-color for the border of an outlined button.

### Additional context
I believe that 

```scss
@mixin outline-color_($color, $query: feature-targeting-functions.all()) {
  $feat-color: feature-targeting-functions.create-target($query, color);

  @include feature-targeting-mixins.targets($feat-color) {
    @include theme-mixins.prop(border-color, $color);
  }
}
```
is taking care of this part and if i'm not mistake is using:

`$outline-color: rgba(theme-variables.prop-value(on-surface), .12) !default;` to set the border color instead of primary.

### Possible solution
Maybe `$outline-color` should be updated to use the right color. 

### Additional Information

Currently i'm using `@include mdc-button.outline-color(var(--mdc-theme-primary));` to set the border color back to primary.
