### ISSUE TITLE
@use "@material/animation" error

### ISSUE THREAD

**Issue by TrySpace** [material-components/material-components-web#5658]
## Bug report
Using simply the `latest react-create-app`, and install `node-sass` with it. Then trying the 2 simple instructions on https://material.io/develop/web/components/animation/ , and use the variables. I get an error about invalid css. While normal sass variables work fine.

### Steps to reproduce
1. Install `@material/animation` like described on `https://material.io/develop/web/components/animation/`
2. Add `@use "@material/animation";` to your `.scss` file
3. Try using `animation: foo-keyframe 175ms animation.$standard-curve-timing-function;`, and replace `foo-keyframe` with an existing keyframe, (Like `App-logo-spin` that comes with the default react-app.

```scss
@use "@material/animation";

.App-logo {
  animation: App-logo-spin 175ms animation.$standard-curve-timing-function;
}

@keyframes App-logo-spin {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
```

### Actual behavior
Error:
```
SassError: Invalid CSS after "...175ms animation": expected expression (e.g. 1px, bold), was ".$standard-curve-ti"
        on line 79 of D:\MyPC\Projects\slider\src\App.scss
>>   animation: App-logo-spin 175ms animation.$standard-curve-timing-function;
```

### Expected behavior
The code not to error 🤷‍♀️

### Environment:
| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | no, only installed `@material/animation`. No dependency is noted on the linked webpage.
| Browser          | Version 80.0.3987.116 (Official Build) (64-bit)
| Operating System | Windows 10

### Additional context
I've tried doing `@import "@material/animation";` but error:
```
SassError: Invalid CSS after " */": expected selector, was "(function webpackUn"
        on line 8 of node_modules/@material/animation/dist/mdc.animation.js
        from line 1 of D:\MyPC\Projects\slider\src\App.scss
>> (function webpackUniversalModuleDefinition(root, factory) {
```

### Possible solution
Perhaps I'm missing some expected dependency, or the sass-loader is not importing it correctly.
I suspect the 2 instructions on the webpage are not enough in isolation, and assume different circumstances. Or I'm just not understanding how sass `@use` works, or how to use the example.
