### ISSUE TITLE
[mdc-card] Text color is not being set based on current theme color palette

### ISSUE THREAD

**Issue by kimurakenshi** [material-components/material-components-web#5698]
## Bug report

Text color is not being set based on current theme color palette

### Steps to reproduce
1. Create a custom theme with different values for `surface` and `on-surface` colors. In my case i'm creating a dark theme where `surface` is black and `on-surface` is white.
2. Compile your scss styles.
3. Check card component styles.

### Actual behavior
Text color is set to black instead of white.

### Expected behavior
Text color should be white since that is the value that `$on-surface` has.

### Additional context
By looking at the base mdc-card styles i see that `background-color` is being set to `surface` but `color` is `inherited`:

```scss
.mdc-card {
  border-radius: 4px;
  background-color: #212121;
  /* @alternate */
  background-color: var(--mdc-theme-surface, #212121);
  /* @alternate */
  position: relative;
  /* @alternate */
  box-shadow: 0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12);
  display: flex;
  flex-direction: column;
  box-sizing: border-box;
}
```
### Possible solution
```scss
@use "@material/theme";

.mdc-card {
 color: theme.$on-surface;
}
```

**Comment by asyncLiz** [comment]
This should be intentional, since the foreground color of content on a card can vary and is not always guaranteed to be the `on-surface` color.

Have you tried adding the `.mdc-theme--on-surface` class to the content that should be the `on-surface` color?

```html
<div class="mdc-card">
  <div class="mdc-theme--on-surface">I should be on-surface</div>
  <div class="mdc-card__actions">
    <div class="mdc-card__action-buttons">
      <button class="mdc-button mdc-card__action mdc-card__action--button">
        <div class="mdc-button__ripple"></div>
        <span class="mdc-button__label">I should not be on-surface</span>
      </button>
    </div>
  </div>
</div>
```

You can also set the background/color of the root element and let things fall through CSS's inherit.

```scss
@use "@material/theme" with (
  $surface: black,
  $on-surface: white
);

html { /* or another root app element */
  background-color: theme.$surface;
  color: theme.$on-surface;
}
```
