### ISSUE TITLE
Permanent drawer does not get same height as content

### ISSUE THREAD

**Issue by deap82** [material-components/material-components-web#575]
### What MDC-Web Version are you using?
Current, as recreated in codepen.

### What browser(s) is this bug affecting?
Would suppose all. I've tested IE11 and latest versions of Chrome and Edge.

### What OS are you using?
Windows 10.

### What are the steps to reproduce the bug?
See codepen: https://codepen.io/deap82/pen/QvgvKP

### What is the expected behavior?
The right border (or any background-color I choose to add) of the .mdc-permanent-drawer element always extends to bottom of page, also when content is higher than drawer.

### What is the actual behavior?
The right-border ends mid air, it goes as long it was when the window was loaded.

**Comment by anton-kachurin** [comment]
https://codepen.io/anton-kachurin/pen/eWRQxM
```CSS
/* To be changed in the component */
.mdc-permanent-drawer {
  height: auto;
}

/* To be changed in the demo */
.demo-content {
  flex: 1;
}

body {
  min-height: 100%;
  height: auto;
}
```

It seems unnecessary to set `height: 100%;` to the drawer because it already uses `flex-direction: column;`. Having `height` set makes the drawer to take not more than the screen height in Chrome and IE.

`flex: 1;` on the wrapper element will force `.mdc-permanent-drawer` and `.demo-main` to grow filling all available vertical space, not just the screen height.

And `min-height: 100%;` instead of `height: 100%;` should be used on the `body` because otherwise its height equals the screen height in Chrome and IE.
