### ISSUE TITLE
Is it possible to get Icon rendering when using SASS @extend rule for <i> ? 

### ISSUE THREAD

**Issue by komali2** [material-components/material-components-web#5934]
## Feature Request

In order to have an `<i>` node display as a `material-icon`, you have to use the following paradigm:

```
<i class="material-icons">start</i>
```

If I try to do the same, but instead of applying the class directly to the node, *extend* the class from SASS, it would look like this:

template/html: 

```
<i>start</i>
```

SASS:

```

i {
  @extend .material-icons;
}
```

This would be fairly convenient, so I don't have to add a class to every single `<i>` in my HTML. However, if I do this now, I don't get the icon itself, but instead my HTML shows the text, `start`. 

Is this possible? Perhaps it already exists and I haven't figured out how to do it right.

**Comment by asyncLiz** [comment]
Thanks for the issue!

Unfortunately this won't be a feature we can support since the Material Icons are not managed by this team, but by the fonts team. 

However, it should be fairly trivial to add the necessary CSS yourself. You can see what all is part of the `.material-icons` class by looking at the stylesheet from https://fonts.googleapis.com/icon?family=Material+Icons.

```css
i {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
```
Hope that helps!
