### ISSUE TITLE
MDC Grid List does not fail gracefully in IE 11

### ISSUE THREAD

**Issue by amsheehan** [material-components/material-components-web#597]
### What MDC-Web Version are you using?

v0.10.0

### What browser(s) is this bug affecting?

IE 11

### What OS are you using?

Windows 8.1 VM running on Virtual Box v5.1.14

### What are the steps to reproduce the bug?

1. Open Explorer and navigate to the [demo site](http://material-components-web.appspot.com/grid-list.html) for grid list.
1. Observe that grid lists do not conform to the spec
1. In the inspector, observe that `mdc-grid-tile` and `mdc-grid-tile__*` are using CSS custom properties

### What is the expected behavior?

Browsers that do not support custom properties should not use css variables or custom properties

### What is the actual behavior?

IE11 uses css vars and custom properties, causing malformed grid lists

**Comment by piotr-cz** [comment]
Confirming on v0.11.0 and Windows 10
![ie11-gridlist](https://cloud.githubusercontent.com/assets/612953/26151222/19cb16ac-3b02-11e7-800e-7600e9d8e52e.png)

**Comment by stsje** [comment]
Setting a fixed width does indeed fix the problem in IE.
```
  .my-grid-list .mdc-grid-tile {
    width: 200px;
  }
```

**Comment by spyhole** [comment]
the same https://github.com/material-components/material-components-web/issues/895

**Comment by protomock** [comment]
It seems like the issue is related to the css variables and for me it was:
```css
 --mdc-grid-list-tile-width: 300px;
 --mdc-theme-primary: rgba(72, 70, 65, 0.75);

```
to address it I added a media query:
```css
@media screen and (-ms-high-contrast: active),
(-ms-high-contrast: none) {
  .mdc-grid-list .mdc-grid-tile {
    width: 300px;
  }
  .mdc-grid-list .mdc-grid-tile__secondary {
    background-color: rgba(72, 70, 65, 0.75);
  }
}
```
if you have webpack, It looks like you could use post-css with [postcss-css-variables](https://www.npmjs.com/package/postcss-css-variables) plugin as well.
