### ISSUE TITLE
[TextField] Cannot use Sass mixins with SCSS modules

### ISSUE THREAD

**Issue by nicholaschiang** [material-components/material-components-web#6081]
## Bug report

I'm using [SCSS modules](https://github.com/css-modules/css-modules) with [Next.js](https://nextjs.org/docs/basic-features/built-in-css-support#sass-support) and am trying to use the Sass mixins provided by `@material/textfield` like so:

```scss
// my-component.module.scss
@use '@material/textfield/_index.scss' as textfield;

.my-text-field {
  @include textfield.outline-color(rgba(0, 0, 0, 0.12));
  @include textfield.outlined-height(32px);
}
```

The `textfield.outlined-height` mixin works properly, as it doesn't reference any classes (i.e. it directly modifies the `.my-text-field` class).

But the `textfield.outline-color` mixin does not work because it references class names that are converted by my SCSS module into unique class names (e.g. `.mdc-notched-outline` becomes `.my-component_mdc-notched-outline__2vuEI`).

### Actual behavior
The `textfield.outline-color` mixin does not work because SCSS modules changes the class names.

### Expected behavior
The class names referenced in the various `@material` mixin files should all be prefixed with the `:global` modifier that explicitly marks them as global class names (and thus prevents them from being modified by SCSS modules).

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 5.1.0
| Browser          | Firefox
| Operating System | Ubuntu 18.04.2

### Additional context

I'm using this with [Next.js's built-in SCSS modules support](https://nextjs.org/docs/basic-features/built-in-css-support#sass-support). 

Also note that right now, I'm importing all of the styling into one global SCSS file (which is bundled with each page). In the future, I'm sure bugs like this one will come up when I try to split that file up (and only include the styling for the components that I use within each component and page).

### Possible solution

I can fix the above described error by simply changing:
```scss
// node_modules/@material/notched-outline/_mixins.scss at line 114
@mixin color($color, $query: feature-targeting-functions.all()) {
  $feat-color: feature-targeting-functions.create-target($query, color);

  .mdc-notched-outline__leading,
  .mdc-notched-outline__notch,
  .mdc-notched-outline__trailing {
    @include feature-targeting-mixins.targets($feat-color) {
      @include theme-mixins.prop(border-color, $color);
    }
  }
}
```

To add the `:global` modifier:
```scss
// node_modules/@material/notched-outline/_mixins.scss at line 114
@mixin color($color, $query: feature-targeting-functions.all()) {
  $feat-color: feature-targeting-functions.create-target($query, color);

  :global(.mdc-notched-outline__leading),
  :global(.mdc-notched-outline__notch),
  :global(.mdc-notched-outline__trailing) {
    @include feature-targeting-mixins.targets($feat-color) {
      @include theme-mixins.prop(border-color, $color);
    }
  }
}
```
