### ISSUE TITLE
It is possible to import for example tab styles without typography styles?

### ISSUE THREAD

**Issue by 7iomka** [material-components/material-components-web#6447]
Hi
I'm new in sass module system (use, forward, ...)
I use your lib like:
```scss
@use '~@material/theme' with (
  $primary: $color-primary,
  $secondary: $color-secondary,
);

// Material components
@use '~@material/tab-bar/mdc-tab';
@use '~@material/tab-bar/mdc-tab-bar';
@use '~@material/tab-scroller/mdc-tab-scroller';
@use '~@material/tab-indicator/mdc-tab-indicator';
@use '~@material/ripple/mdc-ripple';
```

I see that mdc-tab has unwanted typography styles.
Instead of manually override them, it's possible to import only needed stuff?
I read docs related to feature-targeting
```scss
// The above two @includes and the following @include would produce equivalent results:
@include my-component-core-styles(feature-targeting.without(animation));
```
But I don't have ideas how to make this with whole component.
Any ideas?
Thanks!

**Comment by 7iomka** [comment]
How I see this is not possible
```scss
//
// Private
//

@mixin base_($query: functions.all()) {
  $feat-structure: functions.create-target($query, structure);

  @include typography-mixins.typography(button, $query);
```


Maybe you make typography as feature like this?

```scss
@mixin base_($query: functions.all()) {
  $feat-structure: functions.create-target($query, structure);
  $feat-typograpty: functions.create-target($query, typography); // this is hadrcoded!
  
  @include feature-targeting-mixins.targets($feat-typograpty) {
     @include typography-mixins.typography(button, $query);
  }
  
```
