### ISSUE TITLE
Issues in setting up with Rollup

### ISSUE THREAD

**Issue by tvvignesh** [material-components/material-components-web#6492]
Hi. I am trying to setup MWC with rollup but am facing quite a few issues. Can you help?

I have setup rollup to use https://github.com/Anidetrix/rollup-plugin-styles for compiling sass with dart-css loader and the config section looks like this:

```js
styles({
        modules: true,
        mode: "emit",
        sass: {
          impl: 'sass',
          fiber: require('fibers'),
          includePaths: [
            'node_modules'
          ]
        }
      }),
      litcss(),
```

And my main scsss file looks like this:

```
@use "@material/drawer";
@use "@material/list";

@include drawer.core-styles;
@include drawer.dismissible-core-styles;
@include drawer.modal-core-styles;
@include list.core-styles;
```

**Case 1:**

Import just using `@use "@material/drawer";`

I get this:

<img width="701" alt="Capture1" src="https://user-images.githubusercontent.com/1165845/93793867-02f12800-fc55-11ea-8721-80f191f93125.PNG">

I also tried to prefix with a `~` and it had same issues.

**Case 2:**

I added the suffix `_index.css` to make the scss file like this:

```scss
@use "~@material/drawer/_index.scss";
@use "~@material/list/_index.scss";

@include drawer.core-styles;
@include drawer.dismissible-core-styles;
@include drawer.modal-core-styles;
@include list.core-styles;

ion-menu-button {
  display: block;
}
```

(It does not work without the ~) After this, the scss is resolved. But internally the scss refers to other scss files which are being imported like this:  `@use "@material/theme/variables";` This fails because it does not refer to `_variables.scss`

<img width="693" alt="Capture" src="https://user-images.githubusercontent.com/1165845/93794683-0507b680-fc56-11ea-832b-1a21f9bcafde.PNG">

Can you please guide me on how this can be fixed? Any reference rollup implementation which I can use? Thanks.
