### ISSUE TITLE
[QUESTION] Custom Toggle Button creates an issue with MDCRipple

### ISSUE THREAD

**Issue by Hrishikesh-K** [material-components/material-components-web#6550]
Hello.

Before I describe my issue, please let me inform that this is not an **issue** or a **bug**. MDC is working as intended. This is just a question for my specific use case. If this is a wrong place to get help regarding that, my apologies. Please ignore this question or close it.

So, I'm trying to create a custom toggle button. I'm loading Material Icons from my own SVG sprite. I want to animate the icons on click instead of just switching between them. So, I have the setup like this (the live example can be checked [here](https://rippletest.netlify.app/)):

```HTML
<button class = "mdc-icon-button menu-icons" data-mdc-auto-init = "MDCRipple" onclick = "this.classList.toggle('menu-icons-opened');">
  <svg class = "mdc-icon-button__icon menu-icons">
    <use class = "mi-close" xlink:href = "/icon-sprite.svg#mi-close"></use>
    <use class = "mi-menu" xlink:href = "/icon-sprite.svg#mi-menu"></use>
  </svg>
</button>
```

```CSS
.menu-icons
  {
    top: 0;
    left: 0;
    z-index: 10;
    margin: 32px;
    position: fixed;
    overflow: visible;
  }

.menu-icons .mi-menu
  {
    opacity: 1;
    transform: rotateZ(0deg);
    transform-origin: center;
    transition: all 0.25s cubic-bezier(0.4, 0.0, 0.2, 1);
  }

.menu-icons .mi-close
  {
    opacity: 0;
    transform-origin: center;
    transform: rotateZ(-120deg);
    transition: all 0.25s cubic-bezier(0.4, 0.0, 0.2, 1);
  }

.menu-icons-opened .mi-menu
  {
    opacity: 0;
    transform: rotateZ(120deg);
  }

.menu-icons-opened .mi-close
  {
    opacity: 1;
    transform: rotateZ(0deg);
  }
```

As you can see in the live example, the ripple is a little messed up, in the sense, the two circles are appearing at two different places. Is there something I can do to fix it? This isn't a deal breaker for me and I can easily use it without the ripple as the animation is more important for me. But, if I can get both of them working, it'd be great.

Thanks.
