### ISSUE TITLE
[Select] Undefined select mixins

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web#6574]
## Bug report
After upgrading to v8, select can't find mixins (updated the Sass code to latest README). 
I've found out that there is the mixin files that contains them, I can use it with `@use` but it seems I can't include the mixin with `@include`.

### Steps to reproduce
Follow MDC Select README

### Actual behavior
```
Error during compilation:
 ERROR  Failed to compile with 2 errors                                                                                                                                                            15:35:24

 error  in ./resources/sass/app.scss

SassError: Undefined mixin.
    ╷
210 │         @include select.filled-density($value);
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  resources\sass\_material.scss 210:9  @import
  resources\sass\app.scss 14:9         root stylesheet


 error  in ./resources/sass/auth.scss

SassError: Undefined mixin.
    ╷
210 │         @include select.filled-density($value);
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  resources\sass\_material.scss 210:9  @import
  resources\sass\auth.scss 8:9         root stylesheet

```

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 8.0.0
| Browser          | Firefox
| Operating System | Windows 10

**Comment by EstebanG23** [comment]
Hi, could you send the entire `resources\sass\_material.scss` file to investigate.

**Comment by rkiller** [comment]
I'm seeing the same thing. Version 8.0.0 broke mixins for select. AFAIK the other packages are working.

**Comment by EstebanG23** [comment]
With a Sass refactor, MDC Select core-styles were separated from theming, therefore to use select theme mixins you'll need to add
```
@use '....../select-theme'
```
and then use the mixins like so:
```
 @include select-theme.filled-density($value);
```

This is an assumption to the reported bug, to investigate further will need a demo or user code to debug.

**Comment by maicol07** [comment]
@EstebanG23 here is the `_material.scss` file:

```scss
/*!
 * Copyright (c) 2020.  Maicol07 - Tutti i diritti riservati - All rights reserved
 */
@use '~@material/theme' with (
    $primary: $mdc-theme-primary,
    $secondary: $mdc-theme-secondary,
    $background: #fff,
);
@use "~@material/button";
@use "~@material/card";
@use "~@material/checkbox";
@use "~@material/chips";
@use "~@material/circular-progress";
@use "~@material/dialog";
@use "~@material/drawer/mdc-drawer";
@use "~@material/elevation";
@use "~@material/floating-label";
@use "~@material/form-field";
@use "~@material/icon-button";
@use "~@material/line-ripple";
@use "~@material/layout-grid/mdc-layout-grid";
@use "~@material/list/mdc-list";
@use "~@material/menu-surface";
@use "~@material/menu";
@use "~@material/select/select";
@use "~@material/tab-bar/mdc-tab-bar";
@use "~@material/tab-scroller/mdc-tab-scroller";
@use "~@material/tab-indicator/mdc-tab-indicator";
@use "~@material/tab/mdc-tab";
@use "~@material/textfield";
@use "~@material/textfield/icon";
@use "~@material/tooltip/styles";
@use "~@material/top-app-bar/mdc-top-app-bar";
@use "~@material/typography";

// Core styles
@include button.core-styles;
@include card.core-styles;
@include checkbox.core-styles;
@include chips.core-styles;
@include circular-progress.core-styles;
@include dialog.core-styles;
@include elevation.core-styles;
@include floating-label.core-styles;
@include form-field.core-styles;
@include icon.icon-core-styles;
@include icon-button.core-styles;
@include line-ripple.core-styles;
@include menu-surface.core-styles;
@include menu.core-styles;
@include select.core-styles;
@include textfield.core-styles;
@include typography.core-styles;

// Mixins
@use '~@material/select/mixins';

/* ---------------------------
    MDC Buttons
----------------------------- */
$button_densities: ('small': -1, 'comfortable': -2, 'compact': -3);
$button_heights: ('maxi': 44px, 'extra-big': 40px, 'big': 36px, 'small': 32px, 'comfortable': 28px, 'compact': 24px, 'mini': 20px);

@each $name, $value in $button_densities {
    .mdc-button--#{$name} {
        @include button.density($value);
    }
}

.mdc-button--mini {
    @include button.height(map_get($button_heights, 'mini'));
}

.mdc-button--rounded {
    @include button.shape-radius(50%);
}

/* ---------------------------
    MDC Cards
--------------------------- */
.mdc-card {
    padding: 16px;
}

.mdc-card__thumbnail {
    padding-right: 16px;
    font-size: 24px;
}

.mdc-card__title {
    margin-top: 0;
    margin-bottom: 0;
    font-family: var(--mdc-typography-headline1-font-family, $mdc-typography-font-family);
    font-size: 1.25rem;
    font-weight: 500;
    letter-spacing: 0.0125em;
    line-height: 2rem;
}

.mdc-card__subhead {
    display: block;
    font-family: var(--mdc-typography-subtitle1-font-family, $mdc-typography-font-family);
}

.mdc-card__supporting-text {
    display: block;
    padding-top: 16px;
    font-family: var(--mdc-typography-font-family, $mdc-typography-font-family);
}

.mdc-card__title,
.mdc-card__subhead,
.mdc-card__supporting-text {
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    text-decoration: inherit;
    text-transform: inherit;
}

.mdc-card__subhead,
.mdc-card__supporting-text {
    font-size: 0.875rem;
    font-weight: 400;
    letter-spacing: 0.0178571429em;
    line-height: 1.25rem;
    opacity: 0.6;
}

/* ---------------------------
    MDC Chips
--------------------------- */
$chip_densities: ('small': -1, 'comfortable': -2);

@each $name, $value in $chip_densities {
    .mdc-chip--#{$name} {
        @include chips.density($value);
    }
}

/* ---------------------------
    MDC Drawer and Top App Bar
--------------------------- */
body {
    display: flex;
    height: 100vh;
}

.mdc-drawer-app-content {
    position: relative;
    overflow: auto;
    flex: auto;
}

.main-content {
    overflow: auto;
    height: 100%;
}

.mdc-top-app-bar {
    z-index: 7; // Drawer below Top App Bar
    border-bottom: 1px solid var(--mdc-theme-outline-border, rgba(0, 0, 0, 0.12));
    background-color: white;
    box-shadow: inset 0 -1px 0 0 #dadce0;
    color: rgba(0, 0, 0, 0.87);
}

.mdc-top-app-bar *:not(.mdc-menu-surface) {
    color: var(--mdc-theme-text-primary-on-light, #5f6368) !important;
}

.mdc-list-item__graphic {
    font-size: 24px;
}

.mdc-drawer .mdc-list-item--activated,
.mdc-drawer .mdc-list-item--activated .mdc-list-item__graphic {
    color: var(--mdc-theme-text-activated);
}

/* ---------------------------
    MDC Floating Label
--------------------------- */
.mdc-text-field--focused:not(.mdc-text-field--disabled) .mdc-floating-label {
    color: $mdc-theme-primary;
}

/* ---------------------------
    MDC Icon Button
--------------------------- */
.mdc-icon-button:disabled {
    pointer-events: unset;
}

/* ---------------------------
    MDC Linear Progress
--------------------------- */
$colors: ('green': #01c853, 'yellow': #fff200, 'red': #ff3d00, 'blue': #2879ff, 'indigo': #3f51b5, 'gold' : #ffd700, 'orange': #ffa500);

/* @each $name, $code in $colors {
    .mdc-linear-progress.mdc-linear-progress__#{name} {
        @include mixins.bar-color(code)
    }
} */

/* ---------------------------
    MDC Select
--------------------------- */
$select_densities: ('small': -1, 'comfortable': -2, 'compact': -3);

@each $name, $value in $select_densities {
    .mdc-select--#{$name} {
        @include select.filled-density($value);
    }
}

/* ---------------------------
    MDC Text Field
--------------------------- */
.mdc-text-field__icon {
    font-size: 24px;
}

.mdc-text-field input.mdc-text-field__input,
.mdc-text-field span.mdc-floating-label {
    font-family: #{$mdc-typography-font-family};
}

/* ---------------------------
    MDC Theme and Typography
--------------------------- */
:root {
    --mdc-theme-primary: #{$mdc-theme-primary};
    --mdc-theme-secondary: #{$mdc-theme-secondary};
    --mdc-theme-error: #b00020;
    --mdc-theme-outline-border: rgba(0, 0, 0, 0.12);
    --mdc-typography-font-family: #{$mdc-typography-font-family};
    --mdc-typography-button-font-family: #{$mdc-typography-button-font-family};

    @each $type in headline1, headline2, headline3, headline4, headline5, headline6, subtitle1, subtitle2 {
        --mdc-typography-#{$type}-font-family: #{$mdc-typography-headings-font-family};
        --mdc-typography-#{$type}-font-weight: 500;
    }
}
```
