### ISSUE TITLE
[TextField + Icon button] It would be nice to have a grouping of icons

### ISSUE THREAD

**Issue by devslyfox** [material-components/material-components-web#6619]
## Feature Request

![image](https://user-images.githubusercontent.com/5162766/99187631-989ec480-2779-11eb-9a3a-a2521e7faeb7.png)

code example
```html
<div class="text-field-container">
        <label class="mdc-text-field mdc-text-field--filled mdc-text-field--with-leading-icon mdc-text-field--with-trailing-icon">
            <span class="mdc-text-field__ripple"></span>
            <i class="mdc-icon-button material-icons mdc-text-field__icon mdc-text-field__icon--leading " tabindex="0" role="button">phone</i>
            <label class="mdc-floating-label" id="my-label-id">Phone number</label>
            <span class="mdc-text-field__affix mdc-text-field__affix--prefix">+</span>
            <input class="mdc-text-field__input" type="text" aria-labelledby="my-label-id" aria-describedby="asd123" aria-controls="asd123" aria-clear="input-clear"  required>
            <span class="mdc-text-field__affix mdc-text-field__affix--suffix">ru</span>
            <div class="mdc-text-field__group-icon">
                <i id="input-user" class="material-icons mdc-icon-button mdc-text-field__icon mdc-text-field__icon--trailing" tabindex="0" role="button">more_horiz</i>
                <i id="input-clear" class="material-icons mdc-icon-button mdc-text-field__icon mdc-text-field__icon--trailing" tabindex="0" role="button">clear</i>
            </div>
            <div class="mdc-line-ripple"></div>
        </label>
        <div class="mdc-text-field-helper-line">
            <p class="mdc-text-field-helper-text mdc-text-field-helper-text--persistent mdc-text-field-helper-text--validation-msg" id="asd123">Enter your phone number</p>
        </div>
    </div>
```
```scss
.mdc-text-field__group-icon {
    display: inline-flex;
    margin: 0 3px;
    .mdc-icon-button  {
        margin: 0 3px;
    }
}
```

**Comment by devslyfox** [comment]
```scss
.mdc-text-field__group-icon {
    align-self: center;
    display: inline-flex;
    margin: 0 3px;
    .mdc-icon-button  {
        margin: 0 3px;
    }
}
```
