### ISSUE TITLE
[MDC-List] Controls in list item

### ISSUE THREAD

**Issue by aeromac** [material-components/material-components-web#7296]
How do we include a button at the start/end of a list item in v11/12?
.mdc-list-item__start/end both have pointer-events:none, even in the case of .mdc-evolution-list-item--with-trailing-checkbox/radio/switch

**Comment by MaximBalaganskiy** [comment]
```scss
  // restore buttons clickability in lists
  .mdc-icon-button,
  .mdc-fab {
    pointer-events: auto;
  }
```
