### ISSUE TITLE
Hiding a permanent drawer on mobile devices

### ISSUE THREAD

**Issue by kokujin** [material-components/material-components-web#805]
I would like to hide a permanent drawer on mobile devices. In the docs there is a comment that mentions this:

> TODO(sgomes): Give advice on how to hide permanent drawer in mobile.
Maybe @sgomes could point me to some code or post something here?

Thanks

**Comment by Garbee** [comment]
StackOverflow is the best place for technical support questions. All you need to do though is use a media query just like any other responsive design technique.

```css
@media(max-width: 768px) {
    .target-to-drawer {
        display: none;
    }
}
```
