### ISSUE TITLE
[Feature Request] Allow suppression of dark theme / RTL output using global vars

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#839]
A lot of our core component SASS uses the `mdc-rtl` and `mdc-theme-dark` mixes in order to support RTL and Dark mode, respectively. The tradeoff in using these mixins is that they increase the size of the final output. If applications do not need to support RTL and/or dark themes, then this leads to an unnecessary increase in code bloat.

For users that are keen on optimizing their final code size, I propose we do something like the following:

```scss
// globally
$mdc-rtl-enabled: true !default;

// within the mixin
@mixin mdc-rtl(/* ... */) {
  @if ($mdc-rtl-enabled) {
    // mdc-rtl logic
  }
}
```

[dummy example](https://www.sassmeister.com/gist/5c4f518f5f71486798fb907bb2b9175f)

We can do the same thing for dark themes. This would give users an ability to further fine tune the code size footprint of our library.
